@echo off
set ECOSYSTEM_HOME=E:\TK-tarunw\reqsol\ecosystem
set HADOOP_HOME=%ECOSYSTEM_HOME%\hadoop-2.7.3
set SQOOP_HOME=%ECOSYSTEM_HOME%\sqoop-1.4.6.bin__hadoop-0.23
set ZOOKEEPER_HOME=%ECOSYSTEM_HOME%\zookeeper-3.3.6

set HADOOP_COMMON_HOME_LIB=%HADOOP_HOME%\share\hadoop\common\lib\*
set HADOOP_HDFS_HOME_LIB=%HADOOP_HOME%\share\hadoop\hdfs\lib\*
set HADOOP_MAPRED_HOME_LIB=%HADOOP_HOME%\share\hadoop\mapreduce\lib\*
set HADOOP_YARN_HOME_LIB=%HADOOP_HOME%\share\hadoop\yarn\lib\*
set HADOOP_COMMON_LIB=%HADOOP_HOME%\share\hadoop\common\*
set HADOOP_HDFS_LIB=%HADOOP_HOME%\share\hadoop\hdfs\*
set HADOOP_MAPRED_LIB=%HADOOP_HOME%\share\hadoop\mapreduce\*
set HADOOP_YARN_LIB=%HADOOP_HOME%\share\hadoop\yarn\*


set CLASSPATH= %CLASSPATH%;%HADOOP_MAPRED_LIB%;%SQOOP_SERVER_LIB%;%SQOOP_CLIENT_LIB%;%SQOOP_TOOLS_LIB%;%HADOOP_COMMON_HOME_LIB%;%HADOOP_HDFS_HOME_LIB%,%HADOOP_MAPRED_HOME_LIB%;%HADOOP_YARN_HOME_LIB%;%HADOOP_COMMON_LIB%;%HADOOP_HDFS_LIB%;%HADOOP_MAPRED_LIB%;%HADOOP_YARN_LIB%;
